# .github/workflows/ci.yml

name: Logistic Regression CI/CD Pipeline

# Trigger the workflow on push or pull request events to the main branch.
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code.
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment.
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    # Step 3: Install dependencies.
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run the training script.
    - name: Train the logistic regression model
      run: |
        python train.py

    # Step 5: Run the tests.
    - name: Run tests
      run: |
        pytest test_train.py
