# .github/workflows/ci.yml

name: CI Pipeline

# Trigger the workflow on push or pull request events.
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code.
    - name: Checkout code
      uses: actions/checkout@v3  # Updated from @v2 to @v3

    # Step 2: Set up Python environment.
    - name: Set up Python
      uses: actions/setup-python@v4  # Updated from @v2 to @v4
      with:
        python-version: '3.8'

    # Step 3: Install dependencies.
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    # Step 4: Run tests.
    - name: Run tests
      run: |
        pytest test_hello.py
